### PR TITLE
Idmp 462 Use Case 2 Competency Questions

### PR DESCRIPTION
**Pull request by stsilva-osthus**
Updates for Competency questions for Use Case 2

does not cover UC2-CQ2.2, UC2-CQ1c

### CODE REVIEW

**Review by ElisaKendall — CHANGES_REQUESTED** [review]
Would you please remove your changes to the XML catalog file?  They make everything local to your machine rather than relative.  Otherwise I will check further tomorrow, but this has to be revised before we can approve it.  Thanks.

**Comment by mereolog** [comment]
Also there are errors found by the hygiene tests.

**Comment by stsilva-osthus** [comment]
> 

Fixed

**Comment by mereolog** [comment]
I assume that the is blocked by #324 .

**Review by mereolog — CHANGES_REQUESTED** [review]
```
ERROR:https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/NorvascOuterPackaging	is referenced by contains but has no type.	
ERROR:https://spec.pistoiaalliance.org/idmp/ontology/EXT/Examples/AmlodipineExample/PfizerGmbH	is referenced by isPlayedBy but has no type.
```

**Review by mereolog — APPROVED** [review]

**Review by Heiner-Oberkampf — APPROVED** [review]

**Pull request merged**
