### PR TITLE
IDMP-541 - Connect Manufactured Item and Pharmaceutical Product via Transformation

### PR DESCRIPTION
**Pull request by ElisaKendall**
Description: 

1. Augmented the pharmaceutical dose forms ontology to include transformation and the property, hasTransformationProcedure to support  the WHO demo
2. Added a restriction to connect a pharmaceutical dose form to a relevant transformation

Signed-off-by: Elisa Kendall [ekendall@thematix.com](mailto:ekendall@thematix.com)

### CODE REVIEW

**Review by Heiner-Oberkampf — CHANGES_REQUESTED** [review]
1. Property should be "has transformation" not "... procedure. 
2. Need a Restriction to say "pharmaceutical dose form" "has transformation" SOME "transformation" (analog to "has basic dose form")

**Comment by ElisaKendall** [comment]
> 1. Property should be "has transformation" not "... procedure.
> 2. Need a Restriction to say "pharmaceutical dose form" "has transformation" SOME "transformation" (analog to "has basic dose form")

According to the specification, the relationship should be transformation procedure. And we agreed this morning that it is not required -- it should not be some values from but min 0 if there is a restriction at all.  I know this is not identical to what you have, but it is what came out of our meeting this morning and review of the specification (which, according to FDA and the ISO website, will be published with an update next month).

**Comment by Heiner-Oberkampf** [comment]
Ok, then maybe just add the restriction with min 0 to the pharmaceutical dose form and we're good

**Review by Heiner-Oberkampf — APPROVED** [review]
Looks good and right given Elisas comments ISO IDMP standards

**Review by mereolog — DISMISSED** [review]

**Review by tw-osthus — CHANGES_REQUESTED** [review]
Change this to: 
No transformation is needed, if the dose forms of the manufactured item and the pharmaceutical product are equal.

**Comment by ElisaKendall** [comment]
> No transformation is needed, if the dose forms of the manufactured item and the pharmaceutical product are equal.

Done.

**Review by tw-osthus — APPROVED** [review]

**Review by Heiner-Oberkampf — APPROVED** [review]
Reapproved after final adjustments

**Pull request merged**
