### PR TITLE
IDMP-665 - Update the Qlaira example to use the proper IRIs for the SPOR details

### PR DESCRIPTION
**Pull request by ElisaKendall**
Description: Revised SPOR IRIs similarly to what is in the SPOR ontology in the Qlaira example

### CODE REVIEW

**Comment by ElisaKendall** [comment]
Note that this correction does not eliminate punning in the Qlaira example, it only corrects the IRIs.

**Review by tw-osthus — CHANGES_REQUESTED** [review]
The substance IRI should be
https://spor.ema.europa.eu/v2/SubstanceDefinition/{spor-id}

**Comment by tw-osthus** [comment]
/v{version}/MedicinalProductDefinition/{spor-id} should be the IRI for products

https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/substances-products-organisations-referentials-spor-spor-api-v2-specification_en.pdf

**Comment by tw-osthus** [comment]
https://www.youtube.com/watch?v=rNkWj5Kj6iY

**Comment by tw-osthus** [comment]
still can't commit

```
rdf-toolkit: sesame-serializer: This is the pre-commit hook
rdf-toolkit: sesame-serializer: java_home = c:/dev/java11
rdf-toolkit: sesame-serializer: whichJava = c:/dev/java11/bin/java
rdf-toolkit: sesame-serializer: Found rdf-toolkit: /c/dev/pistoia/IDMP/idmp/.git/hooks/rdf-toolkit.jar
rdf-toolkit: sesame-serializer: Launching the sesame-serializer with --source EXT/Examples/QlairaExample.rdf
+ c:/dev/java11/bin/java -Xmx1g -Dorg.clapper.avsl.config=/tmp/sesame-serializer-log -cp /c/dev/pistoia/IDMP/idmp/.git/hooks/rdf-toolkit.jar org.edmcouncil.rdf_toolkit.RdfFormatter --source EXT/Examples/QlairaExample.rdf --target EXT/Examples/QlairaExample.rdfX --target-format rdf-xml --use-dtd-subset --inline-blank-nodes --infer-base-iri
12:02:35.361 ERROR o.e.rdf_toolkit.RdfFormatter - RdfFormatter: stopped by unexpected exception: 
12:02:35.364 ERROR o.e.rdf_toolkit.RdfFormatter - RDFHandlerException: unable to generate/write RDF output
12:02:35.365 ERROR o.e.rdf_toolkit.RdfFormatter - org.eclipse.rdf4j.rio.RDFHandlerException: unable to generate/write RDF output
	at org.edmcouncil.rdf_toolkit.writer.SortedRdfXmlWriter.endRDF(SortedRdfXmlWriter.java:172)
	at org.eclipse.rdf4j.rio.Rio.write(Rio.java:582)
	at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.runOnFile(RdfToolkitRunner.java:218)
	at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.run(RdfToolkitRunner.java:104)
	at org.edmcouncil.rdf_toolkit.RdfFormatter.run(RdfFormatter.java:64)
	at org.edmcouncil.rdf_toolkit.RdfFormatter.main(RdfFormatter.java:47)
Caused by: java.lang.NullPointerException
	at org.edmcouncil.rdf_toolkit.comparator.ComparisonUtils.isCollection(ComparisonUtils.java:138)
	at org.edmcouncil.rdf_toolkit.comparator.BNodeComparator.compareBlankNodesWithInlining(BNodeComparator.java:102)
	at org.edmcouncil.rdf_toolkit.comparator.BNodeComparator.compare(BNodeComparator.java:91)
	at org.edmcouncil.rdf_toolkit.comparator.ResourceComparator.compare(ResourceComparator.java:84)
	at org.edmcouncil.rdf_toolkit.comparator.ResourceComparator.compare(ResourceComparator.java:63)
	at org.edmcouncil.rdf_toolkit.comparator.ResourceComparator.compare(ResourceComparator.java:46)
	at java.base/java.util.TreeMap.put(TreeMap.java:550)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at java.base/java.util.TreeSet.addAll(TreeSet.java:312)
	at org.edmcouncil.rdf_toolkit.model.UnsortedTurtleResourceList.toSorted(UnsortedTurtleResourceList.java:41)
	at org.edmcouncil.rdf_toolkit.writer.SortedRdfXmlWriter.endRDF(SortedRdfXmlWriter.java:162)
	... 5 more

+ rc=1
+ set +x
rdf-toolkit: sesame-serializer: ERROR: sesame-serializer ended with error code 1
rdf-toolkit: sesame-serializer: ERROR: Could not commit your files


git did not exit cleanly (exit code 1) (703 ms @ 10.10.2023 12:02:35)

```

seems to be an issue with blank nodes

**Comment by tw-osthus** [comment]
@ElisaKendall  I have fixed and updated the Qlaira RDF example, but it turned out that we have a bad UC1-CQ3, where we have "fixed" the expected results instead of the wrong query

**Comment by tw-osthus** [comment]
@mereolog we have an error in the spell checker
```
Run python etc/testing/spelling/onto_spellchecker.py --ontology /home/runner/work/idmp/idmp/AboutIDMPDev-ReferenceIndividuals.ttl --spell etc/testing/spelling/domain_specific_spellings.json --filter spec.pistoiaalliance.org
Traceback (most recent call last):
  File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line [12](https://github.com/edmcouncil/idmp/actions/runs/6482571906/job/17602354154#step:7:13)0, in <module>
    check_spelling_in_ontology(
  File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line 95, in check_spelling_in_ontology
    __get_misspellings(
  File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line 75, in __get_misspellings
    __check_word(
  File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line 52, in __check_word
    triple = '|'.join([triple_subject, triple_predicate, object])
TypeError: sequence item 2: expected str instance, type found
Error: Process completed with exit code 1.
```

**Comment by mereolog** [comment]
> @mereolog we have an error in the spell checker
> 
> ```
> Run python etc/testing/spelling/onto_spellchecker.py --ontology /home/runner/work/idmp/idmp/AboutIDMPDev-ReferenceIndividuals.ttl --spell etc/testing/spelling/domain_specific_spellings.json --filter spec.pistoiaalliance.org
> Traceback (most recent call last):
>   File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line [12](https://github.com/edmcouncil/idmp/actions/runs/6482571906/job/17602354154#step:7:13)0, in <module>
>     check_spelling_in_ontology(
>   File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line 95, in check_spelling_in_ontology
>     __get_misspellings(
>   File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line 75, in __get_misspellings
>     __check_word(
>   File "/home/runner/work/idmp/idmp/etc/testing/spelling/onto_spellchecker.py", line 52, in __check_word
>     triple = '|'.join([triple_subject, triple_predicate, object])
> TypeError: sequence item 2: expected str instance, type found
> Error: Process completed with exit code 1.
> ```

The bug is fixed now, but there are several potential misspellings:

hypromellose is possibly misspelled.
pregelatinized is possibly misspelled.
yellowtablets is possibly misspelled.
excepient is possibly misspelled.
individualwoman is possibly misspelled.
thromboembolism is possibly misspelled.
estradiol is possibly misspelled.
valerate is possibly misspelled.

If they are fine, they should be added to https://github.com/edmcouncil/idmp/blob/master/etc/testing/spelling/domain_specific_spellings.json - I can do it if you let me know which ones.

**Review by tw-osthus — APPROVED** [review]

**Review by tw-osthus — APPROVED** [review]

**Review by tw-osthus — APPROVED** [review]

**Review by tw-osthus — APPROVED** [review]

**Review by Heiner-Oberkampf — APPROVED** [review]

**Pull request merged**
